[package]
name = "simple_crawl"
version = "0.1.0"
authors = ["Jon Moroney <darakian@gmail.com>"]

[dependencies]
reqwest = "0.8.7"
select = "0.4.2"
url = "1.7.1"
threadpool = "1.7.1"
num_cpus = "1.0"
